version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql
    env_file:
      - ./.env
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_NAME
    volumes:
      - db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - $PORT:$PORT
    depends_on:
      - db

volumes:
  db:
